### ISSUE TITLE
Needs a note for nitrous users

### ISSUE THREAD

**Issue by dfenjves** [learn-co-curriculum/intro-to-the-shell#237]

**Comment by AnnJohn** [comment]
@dfenjves there's an Intro to Learn track for Nitrous users you can adapt material from. But here are the repos that have info on shell/bash

https://github.com/learn-co-curriculum/intro-to-the-shell-nitrous
https://github.com/learn-co-curriculum/first-console-nitrous
https://github.com/learn-co-curriculum/bash-navigation-nitrous
