### ISSUE TITLE
cant's install -> gem install learn-co

### ISSUE THREAD

**Issue by theasteve** [learn-co-curriculum/intro-to-the-shell#242]
When I try to install learn-co I get the following message:

internal:gem_prelude:1:in `require': cannot load such file -- rubygems.rb (LoadError)
    from <internal:gem_prelude>:1:in`<compiled>'
theAsteve: >

I also tried using: sudo gem install learn-co

But i get the same Error.

**Comment by AnnJohn** [comment]
Hi @theasteve this is not actually the way you install learn and you shouldn't have to in this lesson. 

Could you use the Ask a Question button in Learn and someone from our team will get back to you if you still have questions on installing learn?
