### ISSUE TITLE
Help. Evironment Setup Summary.

### ISSUE THREAD

**Issue by jetendean0z** [learn-co-curriculum/intro-to-the-shell#243]
I'm confused because I'm using a windows computer and all the instructions are for Apple. So right now, I'm testing the commands on the page and the brew doctor command is not working. Is Homebrew necessary for a windows operating system?

**Comment by jetendean0z** [comment]
Same question w/Quicksilver launcher.

**Comment by AnnJohn** [comment]
hi @jetendean0z we use an IDE that we've built instead of you having to use your local environment. Please go to learn.co/ide to download it. 

Thanks
