### ISSUE TITLE
Remove mention of Nitrous - add IDE instructions

### ISSUE THREAD

**Issue by JessRudder** [learn-co-curriculum/intro-to-the-shell#244]
Not sure which tracks include this lesson.

It is one of the first lessons on the pre-work and leads to confusion since no one has "Intro to Learn Nitrous" any longer.

This lesson should either be updated (if it is not shared with other tracks) or replaced so that the info provided here is relevant to admitted students and refers to the IDE, not Nitrous.

**Comment by aturkewi** [comment]
Looks like web dev fundamentals still has this and a question was just asked on it: https://learn.co//lessons/10421?batch_id=482&track_id=10415/&question_id=106409

We should probably update this to just ref the IDE @sgharms @curiositypaths

**Comment by sgharms** [comment]
@JessRudder Thanks for spotting this! We're removing!
